### ISSUE TITLE
Exception in get_official_kernels()

### ISSUE THREAD

**Issue by count-negative** [arcolinux/archlinux-kernel-manager#1]
On the first start of akm I always had an error 
`Exception in get_official_kernels(): time data '05-Mar-2019 21:46' does not match format '%d-%b-%Y %H:%M'`
After a few debug sessions I came to the conclusion that it has to do with my locale that can't parse the March (because Januar and Februar Kernels where fine).

To fix this I suggest to use `locale.setlocale(locale.LC_ALL, "en_US.UTF-8")` before parsing the dates in line 700, functions.py.

Thanks for your work Erik!

P.S. Same for Kernel.py lines 17 & 23

**Comment by DeltaCopy** [comment]
Thanks @count-negative 
I've only just seen your message.
Yes, a `setlocale` change was required due to a parsing issue of datetime.
We can't rely on using `en_us.UTF8` since there is no guarantee that language is set on the user's system.
Instead we use `C.utf8` which is POSIX standards-compliant default locale.

**Comment by count-negative** [comment]
Thanks for fixing!
